<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Application API Rate Limit
    |--------------------------------------------------------------------------
    |
    | This config contains the rate limit for the application API
    | The default is 60 requests per minute, to change the rate limit
    | set the API_RATELIMIT environment variable to the desired number
    |
    */

    'api-ratelimit' => env('API_RATELIMIT', 60),

    /*
    |--------------------------------------------------------------------------
    | WemX Utilities
    |--------------------------------------------------------------------------
    |
    | This config contains Utilities and helper arrays for generic values
    | such as countries, currencies, and other measurements
    |
    */

    'icons' => [
        "<i class='bx bxs-check-shield' ></i>",
        "<i class='bx bxs-shield-x' ></i>",
        "<i class='bx bxs-shield-plus' ></i>",
        "<i class='bx bxs-shield-minus' ></i>",
        "<i class='bx bxs-cube' ></i>",
        "<i class='bx bxs-lock-alt'></i>",
        "<i class='bx bxs-cloud-download'></i>",
        "<i class='bx bxs-cloud-upload'></i>",
        "<i class='bx bxs-user'></i>",
        "<i class='bx bxs-memory-card' ></i>",
        "<i class='bx bxs-chip' ></i>",
        "<i class='bx bxs-microchip' ></i>",
        "<i class='bx bxs-hdd' ></i>",
        "<i class='bx bxs-smile' ></i>",
        "<i class='bx bxs-server'></i>",

        "<i class='bx bxl-discord-alt'></i>",
        "<i class='bx bxs-discount' ></i>",
        "<i class='bx bxs-component'></i>",
        "<i class='bx bx-globe' ></i>",
        "<i class='bx bx-support'></i>",

        "<i class='bx bx-check-shield' ></i>",
        "<i class='bx bx-shield-x' ></i>",
        "<i class='bx bx-shield-plus' ></i>",
        "<i class='bx bx-shield-minus' ></i>",
        "<i class='bx bx-cube' ></i>",
        "<i class='bx bx-lock-alt'></i>",
        "<i class='bx bx-cloud-download'></i>",
        "<i class='bx bx-cloud-upload'></i>",
        "<i class='bx bx-user'></i>",
        "<i class='bx bx-memory-card' ></i>",
        "<i class='bx bx-chip' ></i>",
        "<i class='bx bx-microchip' ></i>",
        "<i class='bx bx-hdd' ></i>",
        "<i class='bx bx-smile' ></i>",
        "<i class='bx bx-server'></i>",

        "<i class='bx bx-wifi'></i>",
        "<i class='bx bx-refresh'></i>",
        "<i class='bx bxs-hot'></i>",
        "<i class='bx bxs-bank'></i>",
        "<i class='bx bxs-battery-charging'></i>",
        "<i class='bx bxs-bell-ring'></i>",
        "<i class='bx bx-calendar-event'></i>",
        "<i class='bx bxs-camera-plus'></i>",
        "<i class='bx bx-car'></i>",
        "<i class='bx bx-cart'></i>",
        "<i class='bx bxs-church'></i>",
        "<i class='bx bxs-city'></i>",
        "<i class='bx bx-coffee'></i>",
        "<i class='bx bxs-crown'></i>",
        "<i class='bx bxs-diamond'></i>",
        "<i class='bx bxs-donate-blood'></i>",
        "<i class='bx bxs-drink'></i>",
        "<i class='bx bx-football'></i>",
        "<i class='bx bxs-game'></i>",
        "<i class='bx bxs-gift'></i>",
        "<i class='bx bx-heart'></i>",
        "<i class='bx bxs-inbox'></i>",
        "<i class='bx bxs-info-circle'></i>",
        "<i class='bx bx-joystick'></i>",
        "<i class='bx bxs-key'></i>",
        "<i class='bx bxs-layer'></i>",
        "<i class='bx bxs-pizza'></i>",
        "<i class='bx bx-planet'></i>",
        "<i class='bx bxs-quote-alt-left'></i>",
        "<i class='bx bx-run'></i>",
        "<i class='bx bxs-school'></i>",
        "<i class='bx bxs-spa'></i>",
        "<i class='bx bxs-star'></i>",
        "<i class='bx bxs-sun'></i>",
        "<i class='bx bxs-tree'></i>",
        "<i class='bx bx-world'></i>",
        "<i class='bx bx-analyse'></i>",
        "<i class='bx bxs-arch'></i>",
        "<i class='bx bx-atom'></i>",
        "<i class='bx bxs-baby-carriage'></i>",
        "<i class='bx bx-ball'></i>",
        "<i class='bx bx-bath'></i>",
        "<i class='bx bx-battery'></i>",
        "<i class='bx bx-bell-plus'></i>",
        "<i class='bx bx-bible'></i>",
        "<i class='bx bx-blanket'></i>",
        "<i class='bx bx-bluetooth'></i>",
        "<i class='bx bxs-book-heart'></i>",
        "<i class='bx bx-bookmark-heart'></i>",
        "<i class='bx bxs-bowling-ball'></i>",
        "<i class='bx bxs-box'></i>",
        "<i class='bx bx-brain'></i>",
        "<i class='bx bx-broadcast'></i>",
        "<i class='bx bxs-brush'></i>",
        "<i class='bx bx-bug-alt'></i>",
        "<i class='bx bx-building-house'></i>",
        "<i class='bx bxs-bulb'></i>",
        "<i class='bx bx-bullseye'></i>",
        "<i class='bx bx-bus-school'></i>",
        "<i class='bx bx-cake'></i>",
        "<i class='bx bx-calculator'></i>",
        "<i class='bx bxs-calendar-heart'></i>",
        "<i class='bx bxs-camera-off'></i>",
        "<i class='bx bx-capsule'></i>",
        "<i class='bx bxs-card'></i>",
        "<i class='bx bx-caret-right-circle'></i>",
        "<i class='bx bx-cctv'></i>",
    ],

    'tailwind-colors' => [
        'rose',
        'pink',
        'fuchsia',
        'purple',
        'violet',
        'indigo',
        'blue',
        'sky',
        'cyan',
        'teal',
        'emerald',
        'green',
        'lime',
        'yellow',
        'amber',
        'orange',
        'red',
        'stone',
        'neutral',
        'zinc',
        'gray',
        'slate'
    ],

    'colors' => [
        'primary' => 'primary',
        'success' => 'green',
        'info' => 'blue',
        'warning' => 'yellow',
        'danger' => 'red',
    ],

    'currencies' => [
        'USD' => [
            'short' => 'USD',
            'name' => 'United States Dollar',
            'symbol' => '$'
        ],
        'EUR' => [
            'short' => 'EUR',
            'name' => 'Euro',
            'symbol' => '€'
        ],
        'JPY' => [
            'short' => 'JPY',
            'name' => 'Japanese Yen',
            'symbol' => '¥'
        ],
        'GBP' => [
            'short' => 'GBP',
            'name' => 'British Pound Sterling',
            'symbol' => '£'
        ],
        'AUD' => [
            'short' => 'AUD',
            'name' => 'Australian Dollar',
            'symbol' => '$'
        ],
        'CAD' => [
            'short' => 'CAD',
            'name' => 'Canadian Dollar',
            'symbol' => '$'
        ],
        'CHF' => [
            'short' => 'CHF',
            'name' => 'Swiss Franc',
            'symbol' => 'Fr'
        ],
        'CNY' => [
            'short' => 'CNY',
            'name' => 'Chinese Yuan',
            'symbol' => '¥'
        ],
        'SEK' => [
            'short' => 'SEK',
            'name' => 'Swedish Krona',
            'symbol' => 'kr'
        ],
        'NZD' => [
            'short' => 'NZD',
            'name' => 'New Zealand Dollar',
            'symbol' => '$'
        ],
        'BRL' => [
            'short' => 'BRL',
            'name' => 'Brazilian Real',
            'symbol' => 'R$'
        ],
    ],

    'countries' => [
        "AF" => "Afghanistan",
        "AL" => "Albania",
        "DZ" => "Algeria",
        "AS" => "American Samoa",
        "AD" => "Andorra",
        "AO" => "Angola",
        "AI" => "Anguilla",
        "AQ" => "Antarctica",
        "AG" => "Antigua and Barbuda",
        "AR" => "Argentina",
        "AM" => "Armenia",
        "AW" => "Aruba",
        "AU" => "Australia",
        "AT" => "Austria",
        "AZ" => "Azerbaijan",
        "BS" => "Bahamas",
        "BH" => "Bahrain",
        "BD" => "Bangladesh",
        "BB" => "Barbados",
        "BY" => "Belarus",
        "BE" => "Belgium",
        "BZ" => "Belize",
        "BJ" => "Benin",
        "BM" => "Bermuda",
        "BT" => "Bhutan",
        "BO" => "Bolivia",
        "BA" => "Bosnia and Herzegovina",
        "BW" => "Botswana",
        "BV" => "Bouvet Island",
        "BR" => "Brazil",
        "BQ" => "British Antarctic Territory",
        "IO" => "British Indian Ocean Territory",
        "VG" => "British Virgin Islands",
        "BN" => "Brunei",
        "BG" => "Bulgaria",
        "BF" => "Burkina Faso",
        "BI" => "Burundi",
        "KH" => "Cambodia",
        "CM" => "Cameroon",
        "CA" => "Canada",
        "CT" => "Canton and Enderbury Islands",
        "CV" => "Cape Verde",
        "KY" => "Cayman Islands",
        "CF" => "Central African Republic",
        "TD" => "Chad",
        "CL" => "Chile",
        "CN" => "China",
        "CX" => "Christmas Island",
        "CC" => "Cocos [Keeling] Islands",
        "CO" => "Colombia",
        "KM" => "Comoros",
        "CG" => "Congo - Brazzaville",
        "CD" => "Congo - Kinshasa",
        "CK" => "Cook Islands",
        "CR" => "Costa Rica",
        "HR" => "Croatia",
        "CU" => "Cuba",
        "CY" => "Cyprus",
        "CZ" => "Czech Republic",
        "CI" => "Côte d’Ivoire",
        "DK" => "Denmark",
        "DJ" => "Djibouti",
        "DM" => "Dominica",
        "DO" => "Dominican Republic",
        "NQ" => "Dronning Maud Land",
        "EC" => "Ecuador",
        "EG" => "Egypt",
        "SV" => "El Salvador",
        "GQ" => "Equatorial Guinea",
        "ER" => "Eritrea",
        "EE" => "Estonia",
        "ET" => "Ethiopia",
        "FK" => "Falkland Islands",
        "FO" => "Faroe Islands",
        "FJ" => "Fiji",
        "FI" => "Finland",
        "FR" => "France",
        "GF" => "French Guiana",
        "PF" => "French Polynesia",
        "TF" => "French Southern Territories",
        "FQ" => "French Southern and Antarctic Territories",
        "GA" => "Gabon",
        "GM" => "Gambia",
        "GE" => "Georgia",
        "DE" => "Germany",
        "GH" => "Ghana",
        "GI" => "Gibraltar",
        "GR" => "Greece",
        "GL" => "Greenland",
        "GD" => "Grenada",
        "GP" => "Guadeloupe",
        "GU" => "Guam",
        "GT" => "Guatemala",
        "GG" => "Guernsey",
        "GN" => "Guinea",
        "GW" => "Guinea-Bissau",
        "GY" => "Guyana",
        "HT" => "Haiti",
        "HM" => "Heard Island and McDonald Islands",
        "HN" => "Honduras",
        "HK" => "Hong Kong SAR China",
        "HU" => "Hungary",
        "IS" => "Iceland",
        "IN" => "India",
        "ID" => "Indonesia",
        "IR" => "Iran",
        "IQ" => "Iraq",
        "IE" => "Ireland",
        "IM" => "Isle of Man",
        "IL" => "Israel",
        "IT" => "Italy",
        "JM" => "Jamaica",
        "JP" => "Japan",
        "JE" => "Jersey",
        "JT" => "Johnston Island",
        "JO" => "Jordan",
        "KZ" => "Kazakhstan",
        "KE" => "Kenya",
        "KI" => "Kiribati",
        "KW" => "Kuwait",
        "KG" => "Kyrgyzstan",
        "LA" => "Laos",
        "LV" => "Latvia",
        "LB" => "Lebanon",
        "LS" => "Lesotho",
        "LR" => "Liberia",
        "LY" => "Libya",
        "LI" => "Liechtenstein",
        "LT" => "Lithuania",
        "LU" => "Luxembourg",
        "MO" => "Macau SAR China",
        "MK" => "Macedonia",
        "MG" => "Madagascar",
        "MW" => "Malawi",
        "MY" => "Malaysia",
        "MV" => "Maldives",
        "ML" => "Mali",
        "MT" => "Malta",
        "MH" => "Marshall Islands",
        "MQ" => "Martinique",
        "MR" => "Mauritania",
        "MU" => "Mauritius",
        "YT" => "Mayotte",
        "MX" => "Mexico",
        "FM" => "Micronesia",
        "MI" => "Midway Islands",
        "MD" => "Moldova",
        "MC" => "Monaco",
        "MN" => "Mongolia",
        "ME" => "Montenegro",
        "MS" => "Montserrat",
        "MA" => "Morocco",
        "MZ" => "Mozambique",
        "MM" => "Myanmar [Burma]",
        "NA" => "Namibia",
        "NR" => "Nauru",
        "NP" => "Nepal",
        "NL" => "Netherlands",
        "AN" => "Netherlands Antilles",
        "NT" => "Neutral Zone",
        "NC" => "New Caledonia",
        "NZ" => "New Zealand",
        "NI" => "Nicaragua",
        "NE" => "Niger",
        "NG" => "Nigeria",
        "NU" => "Niue",
        "NF" => "Norfolk Island",
        "KP" => "North Korea",
        "VD" => "North Vietnam",
        "MP" => "Northern Mariana Islands",
        "NO" => "Norway",
        "OM" => "Oman",
        "PC" => "Pacific Islands Trust Territory",
        "PK" => "Pakistan",
        "PW" => "Palau",
        "PS" => "Palestinian Territories",
        "PA" => "Panama",
        "PZ" => "Panama Canal Zone",
        "PG" => "Papua New Guinea",
        "PY" => "Paraguay",
        "YD" => "People's Democratic Republic of Yemen",
        "PE" => "Peru",
        "PH" => "Philippines",
        "PN" => "Pitcairn Islands",
        "PL" => "Poland",
        "PT" => "Portugal",
        "PR" => "Puerto Rico",
        "QA" => "Qatar",
        "RO" => "Romania",
        "RU" => "Russia",
        "RW" => "Rwanda",
        "RE" => "Réunion",
        "BL" => "Saint Barthélemy",
        "SH" => "Saint Helena",
        "KN" => "Saint Kitts and Nevis",
        "LC" => "Saint Lucia",
        "MF" => "Saint Martin",
        "PM" => "Saint Pierre and Miquelon",
        "VC" => "Saint Vincent and the Grenadines",
        "WS" => "Samoa",
        "SM" => "San Marino",
        "SA" => "Saudi Arabia",
        "SN" => "Senegal",
        "RS" => "Serbia",
        "CS" => "Serbia and Montenegro",
        "SC" => "Seychelles",
        "SL" => "Sierra Leone",
        "SG" => "Singapore",
        "SK" => "Slovakia",
        "SI" => "Slovenia",
        "SB" => "Solomon Islands",
        "SO" => "Somalia",
        "ZA" => "South Africa",
        "GS" => "South Georgia and the South Sandwich Islands",
        "KR" => "South Korea",
        "ES" => "Spain",
        "LK" => "Sri Lanka",
        "SD" => "Sudan",
        "SR" => "Suriname",
        "SJ" => "Svalbard and Jan Mayen",
        "SZ" => "Swaziland",
        "SE" => "Sweden",
        "CH" => "Switzerland",
        "SY" => "Syria",
        "ST" => "São Tomé and Príncipe",
        "TW" => "Taiwan",
        "TJ" => "Tajikistan",
        "TZ" => "Tanzania",
        "TH" => "Thailand",
        "TL" => "Timor-Leste",
        "TG" => "Togo",
        "TK" => "Tokelau",
        "TO" => "Tonga",
        "TT" => "Trinidad and Tobago",
        "TN" => "Tunisia",
        "TR" => "Turkey",
        "TM" => "Turkmenistan",
        "TC" => "Turks and Caicos Islands",
        "TV" => "Tuvalu",
        "UM" => "U.S. Minor Outlying Islands",
        "PU" => "U.S. Miscellaneous Pacific Islands",
        "VI" => "U.S. Virgin Islands",
        "UG" => "Uganda",
        "UA" => "Ukraine",
        "SU" => "Union of Soviet Socialist Republics",
        "AE" => "United Arab Emirates",
        "GB" => "United Kingdom",
        "US" => "United States",
        "UY" => "Uruguay",
        "UZ" => "Uzbekistan",
        "VU" => "Vanuatu",
        "VA" => "Vatican City",
        "VE" => "Venezuela",
        "VN" => "Vietnam",
        "WK" => "Wake Island",
        "WF" => "Wallis and Futuna",
        "EH" => "Western Sahara",
        "YE" => "Yemen",
        "ZM" => "Zambia",
        "ZW" => "Zimbabwe",
        "AX" => "Åland Islands",
    ],
];
